environment:
  WARNINGS_ARE_ERRORS: 1

init:
  ps: |
        Get-Date
        $ErrorActionPreference = "Stop"
install:
  - ps: |
        Import-Module '.\scripts\appveyor-tool.ps1'
        Bootstrap
        
