# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: |
        Bootstrap
        Progress "Downloading external software"
        md C:\Rextsoft
        Invoke-WebRequest http://www.stats.ox.ac.uk/pub/Rtools/goodies/multilib/local320.zip -OutFile "C:\Rextsoft\local320.zip"
        7z x C:\Rextsoft\local320.zip -oC:\Rextsoft -r
        sed "s#^LOCAL_SOFT = d:/RCompile/r-compiling/local/local320#LOCAL_SOFT = C:/Rextsoft#" E:\R\etc\i386\Makeconf > E:\R\etc\i386\Makeconf_tmp
